live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#8ec07c"
duration = 0

[colors.bright]
black = "#7c6f64"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#bdae93"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#928374"
text = "#282828"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.selection]
background = "#ebdbb2"
text = "#928374"

[colors.vi_mode_cursor]
cursor = "#928374"
text = "#282828"

[font]
size = 8.0

[font.normal]
family = "Ubuntu Mono Nerd Font"

[window]
opacity = 1.0
