#!/bin/bash

# Set mod key (Super)
riverctl map normal Super Return spawn foot
riverctl map normal Super D spawn wofi

# Window management
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super Shift C close
riverctl map normal Super Shift E exit

# Move windows
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Resize mode
riverctl declare-mode resize
riverctl map normal Super R enter-mode resize
riverctl map resize Super H resize horizontal -100
riverctl map resize Super L resize horizontal +100
riverctl map resize Super K resize vertical -100
riverctl map resize Super J resize vertical +100
riverctl map resize Super Return enter-mode normal

# Tags (workspaces)
for i in $(seq 1 9); do
    riverctl map normal Super $i set-focused-tags $((1 << ($i - 1)))
    riverctl map normal Super+Shift $i set-view-tags $((1 << ($i - 1)))
done

# Set default layout
riverctl default-layout rivertile
exec rivertile -view-padding 6 -outer-padding 6
