#!/usr/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x dunst > /dev/null || dunst &
pgrep -x redshift > /dev/null || redshift &

killall -q picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom &

# killall -q polybar
# while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# polybar example &

bspc monitor -d 1 2 3 4 5 6

bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#928374"
bspc config active_border_color "#458588"     
bspc config presel_feedback_color "#b8bb26" 

bspc config border_width 1
bspc config window_gap 4

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config bottom_padding 0
bspc config top_padding 0 # 14

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc rule -a floating-status state=floating sticky=on layer=above rectangle=320x140+10+10

# touchpad improvements
xinput list --name-only | grep -i touchpad | while read device; do
	xinput set-prop "$device" "libinput Natural Scrolling Enabled" 1
	xinput set-prop "$device" "libinput Tapping Enabled" 1
	xinput set-prop "$device" "libinput Tapping Button Mapping Enabled" 1 1 0 0 1 3 0
done

# caps lock to escape
setxkbmap -option caps:escape

# wallpaper
feh --bg-scale ~/Pictures/wallpapers/forest_mist.* &
